import type { OnboardingSidebarItem, OnboardingStepContent } from '@/lib/types/onboarding';

export const ONBOARDING_SIDEBAR_ITEMS: OnboardingSidebarItem[] = [
  { id: 1, title: 'Check your KYC', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/check-kyc.svg' },
  { id: 2, title: 'Details from MFCentral', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/details-mfcentral.svg' },
  { id: 3, title: 'Personal Details', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/personal-details.svg' },
  { id: 4, title: 'Tax Details', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/tax-details.svg' },
  { id: 5, title: 'Bank Details', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/bank-details.svg' },
  { id: 6, title: 'Nominee Details', eta: 'Estimated Time: 20 sec', icon: '/assets/onboarding/sidebar/nominee-details.svg' },
];

export const ONBOARDING_STEPS: OnboardingStepContent[] = [
  {
    id: 1,
    slug: '1',
    mobileStepLabel: 'Step 1: Check your KYC',
    progress: 18,
    currentSidebarStage: 1,
    title: 'Check your KYC',
    subtitle: 'Verify your identity to keep your account secure and compliant.',
    fields: [{ label: 'Pan Number', value: 'ABCDE1234F', rounded: 'soft' }],
    question: 'Are you a tax resident of any country other than India?',
    selectedTaxResident: 'no',
    nextStepHref: '/onboarding/2',
    prevStepHref: '/onboarding/1',
  },
  {
    id: 2,
    slug: '2',
    mobileStepLabel: 'Step 1: Check your KYC',
    progress: 34,
    currentSidebarStage: 1,
    title: 'KYC Verification Required',
    subtitle: 'This helps us protect your account and investments.',
    fields: [
      { label: 'Name', rounded: 'pill' },
      { label: 'Email', rounded: 'pill' },
      { label: 'Mobile Number', rounded: 'pill' },
      { label: 'Upload Selfie', rounded: 'soft' },
    ],
    showSelfieUpload: true,
    nextStepHref: '/onboarding/3',
    prevStepHref: '/onboarding/1',
  },
  {
    id: 3,
    slug: '3',
    mobileStepLabel: 'Step 2: Details from MFCentral',
    progress: 52,
    currentSidebarStage: 2,
    title: 'Details from MFCentral',
    subtitle: 'Let’s gather what you already have, so you don’t start from scratch.',
    fields: [
      { label: 'Pan Number', rounded: 'soft' },
      { label: 'Mobile Number', rounded: 'soft' },
    ],
    showSendOtp: true,
    nextStepHref: '/onboarding/4',
    prevStepHref: '/onboarding/2',
  },
  {
    id: 4,
    slug: '4',
    mobileStepLabel: 'Step 2: Details from MFCentral',
    progress: 60,
    currentSidebarStage: 2,
    title: 'Details from MFCentral',
    subtitle: 'Let’s gather what you already have, so you don’t start from scratch.',
    fields: [
      { label: 'Pan Number', rounded: 'soft' },
      { label: 'Mobile Number', rounded: 'soft' },
      { label: 'Enter OTP', rounded: 'soft' },
    ],
    showOtpField: true,
    resendText: 'Resend OTP in 30 seconds',
    nextStepHref: '/onboarding/5',
    prevStepHref: '/onboarding/3',
  },
  {
    id: 5,
    slug: '5',
    mobileStepLabel: 'Step 3: Personal Details',
    progress: 68,
    currentSidebarStage: 3,
    title: 'Personal Details',
    subtitle: 'A few basic details to get you started.',
    fields: [
      { label: 'Name', rounded: 'soft' },
      { label: 'Date of Birth', rounded: 'soft' },
      { label: 'Gender', rounded: 'soft' },
      { label: 'Marital Status', rounded: 'soft' },
      { label: 'Email', rounded: 'soft' },
      { label: 'Address Line 1', rounded: 'soft' },
      { label: 'Address Line 2', rounded: 'soft' },
      { label: 'City', rounded: 'soft' },
      { label: 'State', rounded: 'soft' },
      { label: 'Pincode', rounded: 'soft' },
      { label: 'Country of Birth', rounded: 'soft' },
    ],
    nextStepHref: '/onboarding/6',
    prevStepHref: '/onboarding/4',
    showSendOtp: true,
  },
  {
    id: 6,
    slug: '6',
    mobileStepLabel: 'Step 3: Personal Details',
    progress: 76,
    currentSidebarStage: 3,
    title: 'Personal Details',
    subtitle: 'A few basic details to get you started.',
    fields: [
      { label: 'Name', rounded: 'soft' },
      { label: 'Date of Birth', rounded: 'soft' },
      { label: 'Gender', rounded: 'soft' },
      { label: 'Marital Status', rounded: 'soft' },
      { label: 'Email', rounded: 'soft' },
      { label: 'Enter OTP', rounded: 'soft' },
      { label: 'Address Line 1', rounded: 'soft' },
      { label: 'Address Line 2', rounded: 'soft' },
      { label: 'City', rounded: 'soft' },
      { label: 'State', rounded: 'soft' },
      { label: 'Pincode', rounded: 'soft' },
      { label: 'Country of Birth', rounded: 'soft' },
    ],
    showOtpField: true,
    resendText: 'Resend OTP in 30 seconds',
    nextStepHref: '/onboarding/7',
    prevStepHref: '/onboarding/5',
  },
  {
    id: 7,
    slug: '7',
    mobileStepLabel: 'Step 4: Tax Details',
    progress: 82,
    currentSidebarStage: 4,
    title: 'Tax & Financial Details',
    subtitle: 'Tell us about you; your wealth plan should fit you, not the other way around.',
    fields: [
      { label: 'Occupation', rounded: 'soft' },
      { label: 'Tax Status', rounded: 'soft' },
      { label: 'Annual Income', rounded: 'soft' },
      { label: 'Source of Income', rounded: 'soft' },
      { label: 'Country of Birth', rounded: 'soft' },
    ],
    nextStepHref: '/onboarding/8',
    prevStepHref: '/onboarding/6',
  },
  {
    id: 8,
    slug: '8',
    mobileStepLabel: 'Step 5: Bank Details',
    progress: 88,
    currentSidebarStage: 5,
    title: 'Bank Details',
    subtitle: 'Connect your bank safely for smooth transactions.',
    fields: [
      { label: 'Account Holder Name', rounded: 'soft' },
      { label: 'IFSC Code', rounded: 'soft' },
      { label: 'Account Number', rounded: 'soft' },
      { label: 'Re-enter Account Number', rounded: 'soft' },
      { label: 'Type of Account', rounded: 'soft' },
      { label: 'Mode of Holding', rounded: 'soft' },
    ],
    nextStepHref: '/onboarding/9',
    prevStepHref: '/onboarding/7',
  },
  {
    id: 9,
    slug: '9',
    mobileStepLabel: 'Step 6: Nominee Details',
    progress: 92,
    currentSidebarStage: 6,
    title: 'Nominee Details',
    subtitle: 'Plan for the future, even the \'just in case.\'',
    fields: [
      { label: 'Nominee’s Mobile Number', rounded: 'soft' },
      { label: 'Nominee’s Name', rounded: 'soft' },
      { label: 'Relationship with Investor', rounded: 'soft' },
      { label: 'Nominee’s Date of Birth', rounded: 'soft' },
      { label: 'Nominee’s Pan Number', rounded: 'soft' },
      { label: 'Nominee’s Email', rounded: 'soft' },
    ],
    showSkip: true,
    nextStepHref: '/onboarding/10',
    prevStepHref: '/onboarding/8',
  },
  {
    id: 10,
    slug: '10',
    mobileStepLabel: 'Step 7: Select Fund',
    progress: 95,
    currentSidebarStage: 6,
    title: 'Your journey to wealth just got real.',
    subtitle: 'Let’s get your money working for you',
    fields: [
      { label: 'Enter amount', rounded: 'pill' },
      { label: 'Link this to a goal', rounded: 'soft' },
      { label: 'Enter OTP', rounded: 'pill' },
    ],
    resendText: 'Resend OTP in 30 seconds',
    nextStepHref: '/onboarding/11',
    prevStepHref: '/onboarding/9',
  },
  {
    id: 11,
    slug: '11',
    mobileStepLabel: 'Step 8: Payment Method',
    progress: 98,
    currentSidebarStage: 6,
    title: 'Select Payment Method',
    subtitle: 'Confirm your selected bank and continue securely.',
    fields: [{ label: 'Bank', value: 'HDFC Bank 12341234', rounded: 'soft' }],
    nextStepHref: '/onboarding/12',
    prevStepHref: '/onboarding/10',
  },
  {
    id: 12,
    slug: '12',
    mobileStepLabel: 'Step 9: Completed',
    progress: 100,
    currentSidebarStage: 6,
    title: 'Congratulations!',
    subtitle: '₹1000 Successfully Invested',
    fields: [],
    nextStepHref: '/',
    prevStepHref: '/onboarding/11',
  },
];

export const TRUST_ITEMS = [
  { icon: '/assets/onboarding/trust/no-spam.svg', text: 'No spam calls.' },
  { icon: '/assets/onboarding/trust/private-secure.svg', text: 'Your data is private and secure' },
  { icon: '/assets/onboarding/trust/no-sell.svg', text: "We don't sell your data." },
];

export function getOnboardingStep(stepParam: string) {
  const normalized = stepParam.startsWith('step-') ? stepParam.replace('step-', '') : stepParam;
  const step = Number.parseInt(normalized, 10);
  if (!Number.isFinite(step)) return null;
  return ONBOARDING_STEPS.find((item) => item.id === step) ?? null;
}
